### PR TITLE
add code 2 and some changes in code 1

### LINKED ISSUE #1: Solve a problem on codeforces & make PR
In this issue you have to solve a problem in codeforces & then put the code in `code`  folder with appropriate naming (See the other example from reference)

Keep in mind the following
- Make a separate branch for it & push & make PR from the same.
- Make PR subject & body easy to understand & to the point

Good Luck

### PR DESCRIPTION
**Pull request by Arpitgupta1014**
Hey @sagarmittal1 , Is the code correct that were you expecting or have to change something. Please suggest me. If everything is correct then you can accept the code.
Thank you.

### CODE REVIEW

**Review by sagarmittal1 — CHANGES_REQUESTED** [review]
You have to make the extension of file to .cpp. You have written file in .txt.
That is not acceptable in this case

**Comment by Arpitgupta1014** [comment]
Sure @sagarmitItal1 I will change it.

**Comment by Arpitgupta1014** [comment]
@sagarmittal1 check it now.

**Comment by sagarmittal1** [comment]
LGTM Well done....

**Comment by Arpitgupta1014** [comment]
Thank you, @sagarmittal1 sir, It was delightful to collaborate with you. Looking forward to more collaboration.

**Pull request merged**
